from pydantic import BaseModel, Field
from typing import Optional, Dict, Any


class ChatRequest(BaseModel):
    session_id: str = Field(
        ..., min_length=1, description="Unique session identifier for the conversation"
    )
    message: str = Field(..., min_length=1, description="The message sent by the user")
    user_info: Optional[str] = Field(
        default="", description="Additional contextual information about the user"
    )


class ChatResponse(BaseModel):
    response: str = Field(..., description="The response generated by the agent")
    meta: Dict[str, Any] = Field(
        default_factory=dict, description="Additional metadata about the response"
    )
